bool relative
bool linear
float32 speed # percentage (0.0 - 1.0)

float64[] tcp # [x, y, z]
float64[] goal # [X, Y, Z, RX, RY, RZ]
---
sensor_msgs/JointState joint_state
---
sensor_msgs/JointState joint_state